name: CI

on:
  push:
  pull_request:

jobs:
  check-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t shipit .

      - name: Run Docker container
        run: docker run --rm shipit
